### ISSUE TITLE
solves not all combinations

### ISSUE THREAD

**Issue by appseng** [shunjilin/SlidingTilesPuzzle#2]
I have another project related to this project: [n-Puzzle](https://github.com/appseng/n-puzzle).
It have a solver for 15-puzzle, based on your code (IDA*), but I noticed there are a few combination or initial states, that my program can't solve, because it takes too much memory (up to 1200mb).
I tried to check your project, but ran into some difficulties with compilation.

Could you, please, check the initial state:
 @   9   2  3
  8   1   5 13
14   6   7 11
10 12 15  4
where @ - missing 16th piece(should be at right bottom); on your project, because it's one of hardest, that breaks the code.

**Comment by shunjilin** [comment]
thanks, will check it after work. can I know what kinds of errors you are receiving on compilation? is it regarding the boost dependencies?

**Comment by appseng** [comment]
tryed to compile the project in Windows:
firstly, cmake couldn't find C/CXX compilers, solved it opening the project folder in Visual Studio.
secondly, there was unresolved boost dependency.
lastly, found out that boost should be compiled from sources.

**Comment by shunjilin** [comment]
thanks, I will have to look into a better way to include boost dependencies, or maybe do away with it.

I'm running the instance you mentioned, assuming starting state is "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 0". Its taking very long to run because of state explosion, but I am not having any memory spikes. Memory usage should be limited to F value number of nodes x 4 (per child node), which is minimal. I just peeked at your codebase and I think it might be due to you using vectors (heap allocation) for child nodes, which might result in memory fragmentation? I use arrays (stack allocation) for child nodes, which means they get cleaned up immediately on backtracking of dfs. 

Just to compare when I used regular A* it exhausted 30gb of memory, so this instance might not be feasible to solve in a reasonable amount of time, unless you use a better heuristic, say a pattern database.

**Comment by appseng** [comment]
The starting state "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 0" can't be turned into the goal state "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" but only into "0 1 2 3 4 5 6 7 8 9 10 11 12 13 15 14" i.e. initial state doesn't have solution at all.

30Gb? that's why I use IDA*. Normally it is takes 30-350mb to solve 15-puzzle using my realization based on your code. If it takes more(~12% of all runs), it is almost sure, it won't be solved, despite my program takes only solvable initial states, due to a shuffle algorithm.

**Comment by shunjilin** [comment]
Sorry I meant that I took your starting state "0 9 2 3 8 1 5 13 14 6 7 11 10 12 15 4" and ran against the goal state "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 0". I did not check if the goal is reachable or not, and I am not sure if this is the configuration you meant.

I made changes to the latest commit such that you can specify both starting and goal states, perhaps you can try? 350mb seems quite a lot of memory for IDA*, it should be linear in depth of the search no?

**Comment by appseng** [comment]
You're right: even 350mb is large, I am just making some optimizations in my project, you convinced me that this is the key.

Some initial states need to generate more than 1.5m states in order to make more than 33 steps in solution, my project didn't accept such large numbers.

So I think your code is right, but to solve all possible initial states I need either more memory or great further optimization.
